### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by gpl34** [willghatch/the-unicoder#1]
An error occurred while trying to install the-unicoder. I also tried without sudo and without -i...
Thank you,
Gilles.

```
$ racket --version
Welcome to Racket v6.4.
```

and

```
$ sudo raco pkg install -i the-unicoder
Resolving "the-unicoder" via https://download.racket-lang.org/releases/6.4/catalog/
Resolving "the-unicoder" via https://pkgs.racket-lang.org
Using cached14606173161460617316947 for git://github.com/willghatch/the-unicoder.git
The following uninstalled packages are listed as dependencies of the-unicoder:
   basedir
Would you like to install these dependencies? [Y/n/a/c/?] 
Resolving "basedir" via https://download.racket-lang.org/releases/6.4/catalog/
Resolving "basedir" via https://pkgs.racket-lang.org
Using cached14606173721460617372641 for git://github.com/willghatch/racket-basedir.git
The following out-of-date packages are listed as dependencies of the-unicoder:
   unix-socket-lib (have 1.0, need 1.1)
Would you like to update these dependencies? [Y/n/a/c/?] 
Resolving "unix-socket-lib" via https://download.racket-lang.org/releases/6.4/catalog/
Using cached14606179891460617989264 for https://download.racket-lang.org/releases/6.4/pkgs/unix-socket-lib.zip
raco pkg install: version mismatch for dependency
  for package: the-unicoder
  mismatch packages:
   unix-socket-lib (have 1.0, need 1.1)
```

**Comment by willghatch** [comment]
Hello,

`the-unicoder` depends on a new version of unix-socket-lib that comes with the pre-release version of racket. So you can install it with a snapshot version or wait a few weeks for the next version to come out.

Sorry about that. I should have documented that, but I thought I would just leave off all github documentation until I could link the readme to the hosted scribble docs in a few weeks, and I didn't think people would really take note of the package until then.

On April 14, 2016 4:00:54 AM EDT, gpl34 notifications@github.com wrote:

> An error occurred while trying to install the-unicoder. I also tried
> without sudo and without -i...
> Thank you,
> Gilles.
> 
> ```
> $ racket --version
> Welcome to Racket v6.4.
> ```
> 
> and
> 
> ```
> $ sudo raco pkg install -i the-unicoder
> Resolving "the-unicoder" via
> https://download.racket-lang.org/releases/6.4/catalog/
> Resolving "the-unicoder" via https://pkgs.racket-lang.org
> Using cached14606173161460617316947 for
> git://github.com/willghatch/the-unicoder.git
> The following uninstalled packages are listed as dependencies of
> the-unicoder:
>   basedir
> Would you like to install these dependencies? [Y/n/a/c/?] 
> Resolving "basedir" via
> https://download.racket-lang.org/releases/6.4/catalog/
> Resolving "basedir" via https://pkgs.racket-lang.org
> Using cached14606173721460617372641 for
> git://github.com/willghatch/racket-basedir.git
> The following out-of-date packages are listed as dependencies of
> the-unicoder:
>   unix-socket-lib (have 1.0, need 1.1)
> Would you like to update these dependencies? [Y/n/a/c/?] 
> Resolving "unix-socket-lib" via
> https://download.racket-lang.org/releases/6.4/catalog/
> Using cached14606179891460617989264 for
> https://download.racket-lang.org/releases/6.4/pkgs/unix-socket-lib.zip
> raco pkg install: version mismatch for dependency
>  for package: the-unicoder
>  mismatch packages:
>   unix-socket-lib (have 1.0, need 1.1)
> ```
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/willghatch/the-unicoder/issues/1

## 

Sent from my pocket computer.  Please excuse the lint.

**Comment by gpl34** [comment]
OK, thank you. I'll wait!
